### ISSUE TITLE
Unable to save wallpaper with github build

### ISSUE THREAD

**Issue by easysid** [l3ib/nitrogen#46]
Hi,
I am using Arch linux x64. I downloaded the tarball and ran
```
./bootstrap
./configure
make
```
as given in the instructions. It builds without any errors. However, while using the built nitrogen binary under _src/nitrogen_, I get following errors while selecting a wallpaper and pressing _'Apply'_ to save it. The program sets the wallpaper, but does not save it in _~/.config/nitrogen/bg-saved.cfg_
```
(nitrogen:14594): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed

(nitrogen:14594): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed

(nitrogen:14594): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:14594): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed

(nitrogen:14594): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

(nitrogen:14594): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

(nitrogen:14594): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed
```

I am also using the official nitrogen package from Arch linux repo and it works without any issues. Only the one I build is throwing errors. Any help?

**Comment by daf** [comment]
#53 is probably a duplicate.

**Comment by daf** [comment]
This should be fixed via 2109c85733a4fa9568be276fa0e937ae190a788e and/or 532d5fd1225ebec0b2ccc55d9cff6d588414a9b8

**Comment by Vladimir-csp** [comment]
I'm still experiencing this with current master on Debian Jessie.

built with
```
autoreconf -f -i
./configure
make
fakeroot checkinstall make install
```

Console output while I launched, selected an image, applied, closed:
```
$ nitrogen
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-style' of type `GtkToolbarStyle' from rc file value ""GTK_TOOLBAR_ICONS"" of type `GtkToolbarStyle'
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-icon-size' of type `GtkIconSize' from rc file value ""GTK_ICON_SIZE_SMALL_TOOLBAR"" of type `GtkIconSize'
UNKNOWN ROOT WINDOW TYPE DETECTED, will attempt to set via normal X procedure

(nitrogen:8175): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-style' of type `GtkToolbarStyle' from rc file value ""GTK_TOOLBAR_ICONS"" of type `GtkToolbarStyle'
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-icon-size' of type `GtkIconSize' from rc file value ""GTK_ICON_SIZE_SMALL_TOOLBAR"" of type `GtkIconSize'

(nitrogen:8175): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-style' of type `GtkToolbarStyle' from rc file value ""GTK_TOOLBAR_ICONS"" of type `GtkToolbarStyle'
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-toolbar-icon-size' of type `GtkIconSize' from rc file value ""GTK_ICON_SIZE_SMALL_TOOLBAR"" of type `GtkIconSize'

(nitrogen:8175): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(nitrogen:8175): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed

(nitrogen:8175): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

(nitrogen:8175): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

(nitrogen:8175): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed
```

If I place a proper content into bg-saved.cfg, nitrogen does not overwrite or erase it, but bumps mtime on the file.

**Comment by JamesWrigley** [comment]
I can reproduce this in LXDE on F23 (but not vanilla openbox).

**Comment by daf** [comment]
@Vladimir-csp I find this line rather interesting:

> UNKNOWN ROOT WINDOW TYPE DETECTED, will attempt to set via normal X procedure

This comes from [SetBG.cc#203](https://github.com/l3ib/nitrogen/blob/2109c85733a4fa9568be276fa0e937ae190a788e/src/SetBG.cc#L203) and looks like something found a root window covering (a la Nautilus and friends) but couldn't figure out what kind it was.  In de647b923b4 I introduced a new detection mechanism that might be picking up whatever you're running, but isn't ready to figure out what type of window it is.

What kind of environment are you running in (Distro, DE, etc)?  There may be more paths needed in the codebase here.

@JamesWrigley can you explain in more detail how you reproduced?

**Comment by Vladimir-csp** [comment]
Openbox session with compton compositor, perhaps this causes the check to fail.
But Nitrogen restores background correctly if config contains correct data.

**Comment by JamesWrigley** [comment]
@daf ,
* Compile from source (I had to add `-std=c++11` to `CXXFLAGS` for this to work)
* Open nitrogen and add a folder (I used `/usr/share/backgrounds`, with 'Recurse' checked)
* Select an image (at which point a couple lines of errors are shown, and the desktop background does not change)
* Hit 'Apply' (the rest of the errors @Vladimir-csp posted appear, background still doesn't change)

I can reproduce this on my own machine and a fresh VM. Interestingly, the background I choose momentarily appears when exiting the session (either to log out or shutdown), even though it's not written to `bg-saved.conf`.

**Comment by Vladimir-csp** [comment]
> Interestingly, the background I choose momentarily appears when exiting the session (either to log out or shutdown), even though it's not written to bg-saved.conf.

This might be the moment when compositor exits. Although in my case image is applied right away.

**Comment by daf** [comment]
Ok, I'm able to reproduce with an Openbox session when the `bg-saved.cfg` hasn't been set yet.  Doesn't appear to be related to compton, but I'll make sure to test that path too.  Sort of related, I split of LXDE/pcmanfm support into #63, but that's a different issue.

**Comment by easysid** [comment]
I cannot reproduce this issue

```
export CXXFLAGS="-std=c++11"
autoreconf -f -i
./configure
make
```

I ran *./nitrogen* from src

**bg-saved.cfg**
```
[:0.0]
file=/home/easysid/Pictures/soundbars.jpg
mode=4
bgcolor=#000000

[xin_-1]
file=/home/easysid/Pictures/binary.png
mode=0
bgcolor=#000000

```

The [:0.0] entry corresponds to the stable nitrogen binary from arch repo. The [xin_-1] corresponds to git build nitrogen. I can restore the [xin_-1] wallpaper with `./nitrogen --restore` 

Running bspwm, and compton on Arch linux.

**Comment by daf** [comment]
There's certainly an issue I've discovered with the default X based setter not picking the default properly, causing the first set of warnings - may be the cause of the whole failure.  I just fixed this for Xinerama paths but neglected to try out a non-Xinerama config (Xinerama is enabled even with a single head).

Will fix soon.

**Comment by daf** [comment]
@Vladimir-csp please try with latest master, found a bug in non-xinerama paths.

**Comment by Vladimir-csp** [comment]
Save works!

There is one question I can not test now: if default config in /etc/xdg/nitrogen/bg-saved.cfg contains entries for [:0.0], [xin_0] and [xin_1] to accomodate for possible dual-screen configuration, and user on the machihe with one monitor saves his own configuration, so his config contains only :0.0 section, what would happen if he plugs in a second one and runs nitrogen --restore? Will nitrogen take config for :0.0 from user's config and apply it to his xin_0 and xin_1, or will it take config for xin_0 and xin_1 from default config, bypassing user config?

**Comment by daf** [comment]
This is not a scenario I've tested (I've never had content in `/etc/xdg/nitrogen/` before) but I'm reasonably sure it would not know how to mesh the configurations together.  It would find `~/.config/nitrogen/bg-saved.cfg`, and if it existed, try to find `xin_-1` then `xin_0`/`xin_1` from it.  If those aren't set, there would be no action.

In 532d5fd1225ebec0b2ccc55d9cff6d588414a9b8 I made a change where if the Xinerama extension is simply enabled, no matter if you have >1 screen or not, it will use Xinerama's mode.  This means that in your scenario, one of the monitors will likely have some content, because it won't be changing from `:0.0` to `xin_0`, but it will always have been `xin_0` in single monitor mode.

(this reminds me to make a note of this in release notes as configuration won't automatically update, maybe i should add a porting mechanism for it)

I think I can close this issue again.  #63 will continue as a tangentially related issue.
